Models/Playlist.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;

namespace Eargasm.Models;

public class Playlist
{
    public int Id { get; set; }


    [Required(ErrorMessage = "Please fill out title")]
    [MinLength(3, ErrorMessage = "Minimum 3 characters")]
    public string? Title { get; set; }

    [Required]
    [MinLength(10)]
    public string? Url { get; set; }

    [DataType(DataType.Date)]
    public DateTime Created { get; set; }
    public string? UserId { get; set; }

    public string? imageUrl { get; set; }
    public IdentityUser User { get; set; }

}

Controllers/PlaylistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Eargasm.Models;
using Eargasm.Data;
using Microsoft.AspNetCore.Authorization;
using System.Diagnostics;
using System.Collections.Specialized;
using System.Web;
using System.Threading;

namespace Eargasm.Controllers
{
    [Authorize]
    public class PlaylistController : Controller

    {
        private readonly EargasmContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private object line;

        public PlaylistController(EargasmContext context, UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: Playlist
        public async Task<IActionResult> Index(string searchString)
        {
            if (_context.Playlist == null)
            {
                return Problem("Entity set 'EargasmContext.Playlist'  is null.");
            }

            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            var playlists = from m in _context.Playlist
                            select m;

            playlists = playlists.Where(x => x.UserId.Equals(user.Id));

            if (!String.IsNullOrEmpty(searchString))
            {
                playlists = playlists.Where(s => s.Title!.Contains(searchString));
            }
            return View(await playlists.ToListAsync());
        }

        // GET: Playlist/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Playlist == null)
            {
                return NotFound();
            }

            var playlist = await _context.Playlist
                .FirstOrDefaultAsync(m => m.Id == id);
            if (playlist == null)
            {
                return NotFound();
            }

            return View(playlist);
        }

        // GET: Playlist/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Playlist/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Url")] Playlist playlist)
        {

            string path = new Uri(playlist.Url).AbsolutePath;

            //method to run getcsv script and pass it the path (playlist uid) parameter
            /*
            var processStartInfo = new ProcessStartInfo
            {
                Arguments = string.Format("{0} {1}", "Controllers/getcsv.py", path),
                FileName = "python.exe",
                //FileName = Environment.GetEnvironmentVariable("WINDIR") + (@"\explorer.exe", "C:/Python310"),
                UseShellExecute = false,
                RedirectStandardOutput = true,
                CreateNoWindow = true
            };
            Process.Start(processStartInfo);
            String imgUrl;

            var processStartInfo2 = new ProcessStartInfo
            {
                Arguments = string.Format("{0} {1}", "Controllers/createplaylist.py", path),
                FileName = "python.exe",
                //FileName = Environment.GetEnvironmentVariable("WINDIR") + (@"\explorer.exe", "C:/Python310"),
                UseShellExecute = false,
                RedirectStandardOutput = true,
                CreateNoWindow = true
            };
            Process.Start(processStartInfo2);
*/

            var processStartInfo = new ProcessStartInfo
            {
                Arguments = string.Format("{0} {1} {2}", "Controllers/finalscript.py", path, '"' + playlist.Title + '"'),
                FileName = "python.exe",
                //FileName = Environment.GetEnvironmentVariable("WINDIR") + (@"\explorer.exe", "C:/Python310"),
                UseShellExecute = false,
                RedirectStandardOutput = true,
                CreateNoWindow = true
            };
            Process.Start(processStartInfo);
            String imgUrl;

            // go ahead and save it into the database
            // redirectToAction()
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);
            playlist.UserId = user.Id;
            playlist.Created = DateTime.Now;
            using (var reader = new StreamReader("C:/Users/Glória/Code/GitHub/Sem 4/CryingMaterial/Eargasm/imgUrl.csv"))
            {
                imgUrl = reader.ReadLine();
                reader.Close();

            }
            playlist.imageUrl = imgUrl;

            _context.Playlist.Add(playlist);
            _context.SaveChanges();

            return RedirectToAction("Index");

            return View(playlist);
            // Console.WriteLine(post.Text + " " + post.Title);
            // return RedirectToAction("Test");
        }

        // GET: Playlist/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Playlist == null)
            {
                return NotFound();
            }

            var playlist = await _context.Playlist.FindAsync(id);
            if (playlist == null)
            {
                return NotFound();
            }
            return View(playlist);
        }

        // POST: Playlist/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Url,ImageUrl")] Playlist playlist)
        {
            if (id != playlist.Id)
            {
                return NotFound();
            }
            try
            {
                Console.Write("help" + playlist.imageUrl);
                IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);
                playlist.UserId = user.Id;
                _context.Update(playlist);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PlaylistExists(playlist.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
            return View(playlist);
        }

        // GET: Playlist/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Playlist == null)
            {
                return NotFound();
            }

            var playlist = await _context.Playlist
                .FirstOrDefaultAsync(m => m.Id == id);
            if (playlist == null)
            {
                return NotFound();
            }

            return View(playlist);
        }

        // POST: Playlist/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Playlist == null)
            {
                return Problem("Entity set 'EargasmContext.Playlist'  is null.");
            }
            var playlist = await _context.Playlist.FindAsync(id);
            if (playlist != null)
            {
                _context.Playlist.Remove(playlist);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlaylistExists(int id)
        {
            return (_context.Playlist?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Playlist/Create.cshtml
@model Eargasm.Models.Playlist

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Playlist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Playlist/Delete.cshtml
@model Eargasm.Models.Playlist

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Playlist</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Url)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Url)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Playlist/Details.cshtml
@model Eargasm.Models.Playlist

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Playlist</h4>
    <hr />
    <dl class="row">
        <a href='@Html.DisplayFor(model => model.Url)'>
            <img src="@Html.DisplayFor(model => model.imageUrl)" data-holder-rendered="true"
                style="height: 260px; width: 260px; display: block;">
        </a>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Playlist/Edit.cshtml
@model Eargasm.Models.Playlist

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Playlist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <a href='@Html.DisplayFor(model => model.Url)'>
                <img src="@Html.DisplayFor(model => model.imageUrl)" data-holder-rendered="true"
                    style="height: 260px; width: 260px; display: block;">
            </a>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Playlist/Index.cshtml
@model IEnumerable<Eargasm.Models.Playlist>
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService

@{
    ViewData["Title"] = "Index";
    int counter = 0;

}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Playlist" asp-action="Index">
    <p>
        Title: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <tbody>
        <div class="row">
            @foreach (var item in Model)
            {
                if (counter != 0 && counter % 3 == 0)
                {
                    @:</div>
                    @:<div class="row">
                }

                <div class="col-md-4">
                    <div class="thumbnail">
                        <a href='@Html.DisplayFor(modelItem => item.Url)'>
                            <img src="@Html.DisplayFor(modelItem => item.imageUrl)" data-holder-rendered="true"
                            style="height: 100%; width: 100%; display: block;">
                        </a>
                        <div class="caption">
                            <h3 id="thumbnail-label"> @Html.DisplayFor(modelItem => item.Title)</h3>
                        </div>
                    </div>
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </div>

                counter++;
            }
        </div>
    </tbody>
</table>